/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbankapi

import (
	"encoding/json"
)

// TransactionResourceAttributesCashback If all or part of this transaction was instantly reimbursed in the form of cashback, details of the reimbursement. 
type TransactionResourceAttributesCashback struct {
	// A brief description of why this cashback was paid. 
	Description string `json:"description"`
	Amount CashbackObjectAmount `json:"amount"`
}

// NewTransactionResourceAttributesCashback instantiates a new TransactionResourceAttributesCashback object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceAttributesCashback(description string, amount CashbackObjectAmount) *TransactionResourceAttributesCashback {
	this := TransactionResourceAttributesCashback{}
	this.Description = description
	this.Amount = amount
	return &this
}

// NewTransactionResourceAttributesCashbackWithDefaults instantiates a new TransactionResourceAttributesCashback object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceAttributesCashbackWithDefaults() *TransactionResourceAttributesCashback {
	this := TransactionResourceAttributesCashback{}
	return &this
}

// GetDescription returns the Description field value
func (o *TransactionResourceAttributesCashback) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributesCashback) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TransactionResourceAttributesCashback) SetDescription(v string) {
	o.Description = v
}

// GetAmount returns the Amount field value
func (o *TransactionResourceAttributesCashback) GetAmount() CashbackObjectAmount {
	if o == nil {
		var ret CashbackObjectAmount
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributesCashback) GetAmountOk() (*CashbackObjectAmount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionResourceAttributesCashback) SetAmount(v CashbackObjectAmount) {
	o.Amount = v
}

func (o TransactionResourceAttributesCashback) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionResourceAttributesCashback struct {
	value *TransactionResourceAttributesCashback
	isSet bool
}

func (v NullableTransactionResourceAttributesCashback) Get() *TransactionResourceAttributesCashback {
	return v.value
}

func (v *NullableTransactionResourceAttributesCashback) Set(val *TransactionResourceAttributesCashback) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceAttributesCashback) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceAttributesCashback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceAttributesCashback(val *TransactionResourceAttributesCashback) *NullableTransactionResourceAttributesCashback {
	return &NullableTransactionResourceAttributesCashback{value: val, isSet: true}
}

func (v NullableTransactionResourceAttributesCashback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceAttributesCashback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


