/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbankapi

import (
	"encoding/json"
)

// UpdateTransactionCategoryRequestData The category to set on the transaction. Set this entire key to `null` de-categorize a transaction. 
type UpdateTransactionCategoryRequestData struct {
	// The type of this resource: `categories`
	Type string `json:"type"`
	// The unique identifier of the category, as returned by the `/categories` endpoint. 
	Id string `json:"id"`
}

// NewUpdateTransactionCategoryRequestData instantiates a new UpdateTransactionCategoryRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTransactionCategoryRequestData(type_ string, id string) *UpdateTransactionCategoryRequestData {
	this := UpdateTransactionCategoryRequestData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewUpdateTransactionCategoryRequestDataWithDefaults instantiates a new UpdateTransactionCategoryRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTransactionCategoryRequestDataWithDefaults() *UpdateTransactionCategoryRequestData {
	this := UpdateTransactionCategoryRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateTransactionCategoryRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateTransactionCategoryRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateTransactionCategoryRequestData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *UpdateTransactionCategoryRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateTransactionCategoryRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateTransactionCategoryRequestData) SetId(v string) {
	o.Id = v
}

func (o UpdateTransactionCategoryRequestData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateTransactionCategoryRequestData struct {
	value *UpdateTransactionCategoryRequestData
	isSet bool
}

func (v NullableUpdateTransactionCategoryRequestData) Get() *UpdateTransactionCategoryRequestData {
	return v.value
}

func (v *NullableUpdateTransactionCategoryRequestData) Set(val *UpdateTransactionCategoryRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTransactionCategoryRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTransactionCategoryRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTransactionCategoryRequestData(val *UpdateTransactionCategoryRequestData) *NullableUpdateTransactionCategoryRequestData {
	return &NullableUpdateTransactionCategoryRequestData{value: val, isSet: true}
}

func (v NullableUpdateTransactionCategoryRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTransactionCategoryRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


