/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbankapi

import (
	"encoding/json"
)

// CategoryResourceRelationshipsChildrenDataInner struct for CategoryResourceRelationshipsChildrenDataInner
type CategoryResourceRelationshipsChildrenDataInner struct {
	// The type of this resource: `categories`
	Type string `json:"type"`
	// The unique identifier of the resource within its type. 
	Id string `json:"id"`
}

// NewCategoryResourceRelationshipsChildrenDataInner instantiates a new CategoryResourceRelationshipsChildrenDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryResourceRelationshipsChildrenDataInner(type_ string, id string) *CategoryResourceRelationshipsChildrenDataInner {
	this := CategoryResourceRelationshipsChildrenDataInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewCategoryResourceRelationshipsChildrenDataInnerWithDefaults instantiates a new CategoryResourceRelationshipsChildrenDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryResourceRelationshipsChildrenDataInnerWithDefaults() *CategoryResourceRelationshipsChildrenDataInner {
	this := CategoryResourceRelationshipsChildrenDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *CategoryResourceRelationshipsChildrenDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CategoryResourceRelationshipsChildrenDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CategoryResourceRelationshipsChildrenDataInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CategoryResourceRelationshipsChildrenDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryResourceRelationshipsChildrenDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryResourceRelationshipsChildrenDataInner) SetId(v string) {
	o.Id = v
}

func (o CategoryResourceRelationshipsChildrenDataInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableCategoryResourceRelationshipsChildrenDataInner struct {
	value *CategoryResourceRelationshipsChildrenDataInner
	isSet bool
}

func (v NullableCategoryResourceRelationshipsChildrenDataInner) Get() *CategoryResourceRelationshipsChildrenDataInner {
	return v.value
}

func (v *NullableCategoryResourceRelationshipsChildrenDataInner) Set(val *CategoryResourceRelationshipsChildrenDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryResourceRelationshipsChildrenDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryResourceRelationshipsChildrenDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryResourceRelationshipsChildrenDataInner(val *CategoryResourceRelationshipsChildrenDataInner) *NullableCategoryResourceRelationshipsChildrenDataInner {
	return &NullableCategoryResourceRelationshipsChildrenDataInner{value: val, isSet: true}
}

func (v NullableCategoryResourceRelationshipsChildrenDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryResourceRelationshipsChildrenDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


