/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbankapi

import (
	"encoding/json"
	"time"
)

// TransactionResourceAttributes struct for TransactionResourceAttributes
type TransactionResourceAttributes struct {
	// The current processing status of this transaction, according to whether or not this transaction has settled or is still held. 
	Status NullableTransactionStatusEnum `json:"status"`
	// The original, unprocessed text of the transaction. This is often not a perfect indicator of the actual merchant, but it is useful for reconciliation purposes in some cases. 
	RawText NullableString `json:"rawText"`
	// A short description for this transaction. Usually the merchant name for purchases. 
	Description string `json:"description"`
	// Attached message for this transaction, such as a payment message, or a transfer note. 
	Message NullableString `json:"message"`
	// Boolean flag set to true on transactions that support the use of categories. 
	IsCategorizable bool `json:"isCategorizable"`
	HoldInfo NullableTransactionResourceAttributesHoldInfo `json:"holdInfo"`
	RoundUp NullableTransactionResourceAttributesRoundUp `json:"roundUp"`
	Cashback NullableTransactionResourceAttributesCashback `json:"cashback"`
	Amount TransactionResourceAttributesAmount `json:"amount"`
	ForeignAmount NullableTransactionResourceAttributesForeignAmount `json:"foreignAmount"`
	// The date-time at which this transaction settled. This field will be `null` for transactions that are currently in the `HELD` status. 
	SettledAt NullableTime `json:"settledAt"`
	// The date-time at which this transaction was first encountered. 
	CreatedAt time.Time `json:"createdAt"`
}

// NewTransactionResourceAttributes instantiates a new TransactionResourceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResourceAttributes(status NullableTransactionStatusEnum, rawText NullableString, description string, message NullableString, isCategorizable bool, holdInfo NullableTransactionResourceAttributesHoldInfo, roundUp NullableTransactionResourceAttributesRoundUp, cashback NullableTransactionResourceAttributesCashback, amount TransactionResourceAttributesAmount, foreignAmount NullableTransactionResourceAttributesForeignAmount, settledAt NullableTime, createdAt time.Time) *TransactionResourceAttributes {
	this := TransactionResourceAttributes{}
	this.Status = status
	this.RawText = rawText
	this.Description = description
	this.Message = message
	this.IsCategorizable = isCategorizable
	this.HoldInfo = holdInfo
	this.RoundUp = roundUp
	this.Cashback = cashback
	this.Amount = amount
	this.ForeignAmount = foreignAmount
	this.SettledAt = settledAt
	this.CreatedAt = createdAt
	return &this
}

// NewTransactionResourceAttributesWithDefaults instantiates a new TransactionResourceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResourceAttributesWithDefaults() *TransactionResourceAttributes {
	this := TransactionResourceAttributes{}
	return &this
}

// GetStatus returns the Status field value
// If the value is explicit nil, the zero value for TransactionStatusEnum will be returned
func (o *TransactionResourceAttributes) GetStatus() TransactionStatusEnum {
	if o == nil || o.Status.Get() == nil {
		var ret TransactionStatusEnum
		return ret
	}

	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetStatusOk() (*TransactionStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// SetStatus sets field value
func (o *TransactionResourceAttributes) SetStatus(v TransactionStatusEnum) {
	o.Status.Set(&v)
}

// GetRawText returns the RawText field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetRawText() string {
	if o == nil || o.RawText.Get() == nil {
		var ret string
		return ret
	}

	return *o.RawText.Get()
}

// GetRawTextOk returns a tuple with the RawText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetRawTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawText.Get(), o.RawText.IsSet()
}

// SetRawText sets field value
func (o *TransactionResourceAttributes) SetRawText(v string) {
	o.RawText.Set(&v)
}

// GetDescription returns the Description field value
func (o *TransactionResourceAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TransactionResourceAttributes) SetDescription(v string) {
	o.Description = v
}

// GetMessage returns the Message field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TransactionResourceAttributes) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}

	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// SetMessage sets field value
func (o *TransactionResourceAttributes) SetMessage(v string) {
	o.Message.Set(&v)
}

// GetIsCategorizable returns the IsCategorizable field value
func (o *TransactionResourceAttributes) GetIsCategorizable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCategorizable
}

// GetIsCategorizableOk returns a tuple with the IsCategorizable field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetIsCategorizableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCategorizable, true
}

// SetIsCategorizable sets field value
func (o *TransactionResourceAttributes) SetIsCategorizable(v bool) {
	o.IsCategorizable = v
}

// GetHoldInfo returns the HoldInfo field value
// If the value is explicit nil, the zero value for TransactionResourceAttributesHoldInfo will be returned
func (o *TransactionResourceAttributes) GetHoldInfo() TransactionResourceAttributesHoldInfo {
	if o == nil || o.HoldInfo.Get() == nil {
		var ret TransactionResourceAttributesHoldInfo
		return ret
	}

	return *o.HoldInfo.Get()
}

// GetHoldInfoOk returns a tuple with the HoldInfo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetHoldInfoOk() (*TransactionResourceAttributesHoldInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.HoldInfo.Get(), o.HoldInfo.IsSet()
}

// SetHoldInfo sets field value
func (o *TransactionResourceAttributes) SetHoldInfo(v TransactionResourceAttributesHoldInfo) {
	o.HoldInfo.Set(&v)
}

// GetRoundUp returns the RoundUp field value
// If the value is explicit nil, the zero value for TransactionResourceAttributesRoundUp will be returned
func (o *TransactionResourceAttributes) GetRoundUp() TransactionResourceAttributesRoundUp {
	if o == nil || o.RoundUp.Get() == nil {
		var ret TransactionResourceAttributesRoundUp
		return ret
	}

	return *o.RoundUp.Get()
}

// GetRoundUpOk returns a tuple with the RoundUp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetRoundUpOk() (*TransactionResourceAttributesRoundUp, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoundUp.Get(), o.RoundUp.IsSet()
}

// SetRoundUp sets field value
func (o *TransactionResourceAttributes) SetRoundUp(v TransactionResourceAttributesRoundUp) {
	o.RoundUp.Set(&v)
}

// GetCashback returns the Cashback field value
// If the value is explicit nil, the zero value for TransactionResourceAttributesCashback will be returned
func (o *TransactionResourceAttributes) GetCashback() TransactionResourceAttributesCashback {
	if o == nil || o.Cashback.Get() == nil {
		var ret TransactionResourceAttributesCashback
		return ret
	}

	return *o.Cashback.Get()
}

// GetCashbackOk returns a tuple with the Cashback field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetCashbackOk() (*TransactionResourceAttributesCashback, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cashback.Get(), o.Cashback.IsSet()
}

// SetCashback sets field value
func (o *TransactionResourceAttributes) SetCashback(v TransactionResourceAttributesCashback) {
	o.Cashback.Set(&v)
}

// GetAmount returns the Amount field value
func (o *TransactionResourceAttributes) GetAmount() TransactionResourceAttributesAmount {
	if o == nil {
		var ret TransactionResourceAttributesAmount
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetAmountOk() (*TransactionResourceAttributesAmount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionResourceAttributes) SetAmount(v TransactionResourceAttributesAmount) {
	o.Amount = v
}

// GetForeignAmount returns the ForeignAmount field value
// If the value is explicit nil, the zero value for TransactionResourceAttributesForeignAmount will be returned
func (o *TransactionResourceAttributes) GetForeignAmount() TransactionResourceAttributesForeignAmount {
	if o == nil || o.ForeignAmount.Get() == nil {
		var ret TransactionResourceAttributesForeignAmount
		return ret
	}

	return *o.ForeignAmount.Get()
}

// GetForeignAmountOk returns a tuple with the ForeignAmount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetForeignAmountOk() (*TransactionResourceAttributesForeignAmount, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForeignAmount.Get(), o.ForeignAmount.IsSet()
}

// SetForeignAmount sets field value
func (o *TransactionResourceAttributes) SetForeignAmount(v TransactionResourceAttributesForeignAmount) {
	o.ForeignAmount.Set(&v)
}

// GetSettledAt returns the SettledAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TransactionResourceAttributes) GetSettledAt() time.Time {
	if o == nil || o.SettledAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.SettledAt.Get()
}

// GetSettledAtOk returns a tuple with the SettledAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionResourceAttributes) GetSettledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledAt.Get(), o.SettledAt.IsSet()
}

// SetSettledAt sets field value
func (o *TransactionResourceAttributes) SetSettledAt(v time.Time) {
	o.SettledAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *TransactionResourceAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TransactionResourceAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TransactionResourceAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o TransactionResourceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status.Get()
	}
	if true {
		toSerialize["rawText"] = o.RawText.Get()
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["message"] = o.Message.Get()
	}
	if true {
		toSerialize["isCategorizable"] = o.IsCategorizable
	}
	if true {
		toSerialize["holdInfo"] = o.HoldInfo.Get()
	}
	if true {
		toSerialize["roundUp"] = o.RoundUp.Get()
	}
	if true {
		toSerialize["cashback"] = o.Cashback.Get()
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["foreignAmount"] = o.ForeignAmount.Get()
	}
	if true {
		toSerialize["settledAt"] = o.SettledAt.Get()
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionResourceAttributes struct {
	value *TransactionResourceAttributes
	isSet bool
}

func (v NullableTransactionResourceAttributes) Get() *TransactionResourceAttributes {
	return v.value
}

func (v *NullableTransactionResourceAttributes) Set(val *TransactionResourceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResourceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResourceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResourceAttributes(val *TransactionResourceAttributes) *NullableTransactionResourceAttributes {
	return &NullableTransactionResourceAttributes{value: val, isSet: true}
}

func (v NullableTransactionResourceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResourceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


