/*
Up API

The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upbankapi

import (
	"encoding/json"
)

// AccountResourceAttributesBalance The available balance of the account, taking into account any amounts that are currently on hold. 
type AccountResourceAttributesBalance struct {
	// The ISO 4217 currency code. 
	CurrencyCode string `json:"currencyCode"`
	// The amount of money, formatted as a string in the relevant currency. For example, for an Australian dollar value of $10.56, this field will be `\"10.56\"`. The currency symbol is not included in the string. 
	Value string `json:"value"`
	// The amount of money in the smallest denomination for the currency, as a 64-bit integer.  For example, for an Australian dollar value of $10.56, this field will be `1056`. 
	ValueInBaseUnits int32 `json:"valueInBaseUnits"`
}

// NewAccountResourceAttributesBalance instantiates a new AccountResourceAttributesBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResourceAttributesBalance(currencyCode string, value string, valueInBaseUnits int32) *AccountResourceAttributesBalance {
	this := AccountResourceAttributesBalance{}
	this.CurrencyCode = currencyCode
	this.Value = value
	this.ValueInBaseUnits = valueInBaseUnits
	return &this
}

// NewAccountResourceAttributesBalanceWithDefaults instantiates a new AccountResourceAttributesBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResourceAttributesBalanceWithDefaults() *AccountResourceAttributesBalance {
	this := AccountResourceAttributesBalance{}
	return &this
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *AccountResourceAttributesBalance) GetCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributesBalance) GetCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *AccountResourceAttributesBalance) SetCurrencyCode(v string) {
	o.CurrencyCode = v
}

// GetValue returns the Value field value
func (o *AccountResourceAttributesBalance) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributesBalance) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AccountResourceAttributesBalance) SetValue(v string) {
	o.Value = v
}

// GetValueInBaseUnits returns the ValueInBaseUnits field value
func (o *AccountResourceAttributesBalance) GetValueInBaseUnits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ValueInBaseUnits
}

// GetValueInBaseUnitsOk returns a tuple with the ValueInBaseUnits field value
// and a boolean to check if the value has been set.
func (o *AccountResourceAttributesBalance) GetValueInBaseUnitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueInBaseUnits, true
}

// SetValueInBaseUnits sets field value
func (o *AccountResourceAttributesBalance) SetValueInBaseUnits(v int32) {
	o.ValueInBaseUnits = v
}

func (o AccountResourceAttributesBalance) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["valueInBaseUnits"] = o.ValueInBaseUnits
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResourceAttributesBalance struct {
	value *AccountResourceAttributesBalance
	isSet bool
}

func (v NullableAccountResourceAttributesBalance) Get() *AccountResourceAttributesBalance {
	return v.value
}

func (v *NullableAccountResourceAttributesBalance) Set(val *AccountResourceAttributesBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResourceAttributesBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResourceAttributesBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResourceAttributesBalance(val *AccountResourceAttributesBalance) *NullableAccountResourceAttributesBalance {
	return &NullableAccountResourceAttributesBalance{value: val, isSet: true}
}

func (v NullableAccountResourceAttributesBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResourceAttributesBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


